export const copy = {
 en: {
  name:'Lenar Sabirov',role:'Product Manager',tagline:'Payment products. AI tools.\nUseful automation.',
  intro:'I’m Lenar, a product manager focused on payment products, AI tools and independent automation projects. I enjoy turning complex workflows into simple, useful products, from idea to working solution, and collaborating with engineers, designers and business stakeholders.',
  nav:{about:'About',experience:'Experience',projects:'Projects'},projects:'Selected projects',experience:'Experience',earlier:'Earlier experience',education:'Education',degree:'Bachelor’s degree in Accounting, Analysis and Audit',university:'Kazan Innovative University · 2017',skip:'Skip to content',close:'Close project',details:'Read about',illustration:'Concept illustration',problem:'The idea',solution:'How it works',stack:'Built with',back:'Back to projects',visit:'Visit website',top:'Back to top',contact:'Get in touch',footer:'Lenar Sabirov · Product Manager',
  projectsList:[
   {id:'ludobot',name:'Ludobot',summary:'Autonomous trading on Hyperliquid with AI decisions and risk controls.',tags:['AI','Trading'],idea:'Bring market analysis, trading decisions and execution into a single autonomous workflow, with visibility into what the system is doing.',solution:'Strategies collect market and account data, request a decision from an AI model, apply code-enforced risk controls and execute orders on Hyperliquid. A web dashboard brings together strategies, positions, performance and per-cycle logs.',stack:['Go','Hyperliquid API','OpenRouter','JavaScript']},
   {id:'health-tracker',name:'Health Tracker',url:'https://health.asg.travel/',summary:'An extended MCP integration connecting AI assistants to Google Health.',tags:['AI','Health'],idea:'Make health data accessible within an AI conversation, with tools that support everyday tracking.',solution:'An extension of an existing open-source Google Health MCP server, with custom nutrition logging and a hosted connection flow for additional users. The project connects an existing data source to an assistant and adds practical tools around it.',stack:['MCP','Google Health','OAuth','Node.js']},
   {id:'context-study',name:'Context Study',summary:'A shared learning history for AI English tutors, across sessions and models.',tags:['AI','Education'],idea:'Keep learning continuous when a conversation ends or the student switches to another AI tutor.',solution:'An MCP server stores lessons, writing samples and recurring errors in a shared journal. Each tutor reads the same history while maintaining its own assessment and teaching plan. The next lesson builds on what has already been learned.',stack:['Python','MCP','JSON-RPC','Local storage']},
   {id:'defi-assist',name:'DeFi Assist',url:'https://defiassist.github.io/add-on',summary:'Crypto wallet and DeFi portfolio tracking inside Google Sheets.',tags:['Crypto','Automation'],idea:'Bring a fragmented crypto portfolio into a familiar, flexible workspace: a spreadsheet.',solution:'A Google Sheets add-on imports balances, transactions and DeFi positions using the DeBank API. Scheduled updates keep wallet sheets current, while a consolidated dashboard combines multiple wallets for portfolio reporting.',stack:['Google Apps Script','JavaScript','Google Sheets','DeBank API']}
  ],
  roles:[
   {period:'2022 — PRESENT',company:'Independent Projects',title:'Independent Product Development',description:'After leaving MTS Bank, I moved into independent projects. My current work spans autonomous trading, AI integrations for health data, continuous English learning and crypto portfolio reporting.',tags:['Product discovery','AI workflows','Automation']},
   {period:'JUL 2020 — MAY 2022',company:'MTS Bank',title:'Product Lead · Faster Payments & Acquiring',description:'Helped launch C2B and B2C services on Russia’s Faster Payments System. Defined user journeys, business requirements and APIs across mobile banking, merchant integrations, POS terminals and e-commerce. Managed the backlog and coordinated with analysts, architects and development teams.',result:'Coordinated the bank’s C2B rollout across MTS retail stores. By month four, the service accounted for 10% of the network’s total sales.',tags:['Payments','API integrations','Product delivery','BPMN']},
   {period:'MAY 2019 — JUL 2020',company:'Ak Bars Bank',title:'Product Manager · Merchant Acquiring',description:'Worked on the C2B payments launch, covering requirements, business processes, financial modelling and acceptance testing. Supported major partner integrations and coordinated operational requirements with payment infrastructure stakeholders.',result:'The C2B service reached production, and acquiring transaction reconciliation was automated.',tags:['Merchant acquiring','Financial modelling','Process automation']},
   {period:'DEC 2017 — MAR 2019',company:'Germes Logistics',title:'Marketing · Internal Tools & Automation',description:'Alongside digital marketing, built tools for logistics, sales and finance: return-trip carrier matching, load notifications and a quotation builder. Created performance dashboards and a carrier payment scheduling tool that accounted for customer receivables.',tags:['Internal tools','Logistics','Dashboards']},
   {period:'JUN 2016 — AUG 2017',company:'Effective Solutions',title:'Project Manager',description:'Turned client needs into interactive prototypes, user journeys and API requirements for web and mobile products. Defined order allocation and trip pricing logic, coordinated development and testing, and incorporated client feedback.',tags:['Prototyping','API requirements','Delivery','Axure']}
  ],
  earlyRoles:[
   {period:'AUG — DEC 2017',company:'Independent Projects',title:'Project Lead',description:'Scoped MVPs, assembled teams and coordinated web development, client requirements, backlogs and advertising campaigns.'},
   {period:'MAR — AUG 2016',company:'SAP Invest',title:'Marketing Analyst · Part-time',description:'Analysed advertising performance, maintained the financial model and implemented a CRM with custom PHP and SQL calculations.'},
   {period:'MAY 2015 — APR 2016',company:'Artus',title:'Project Manager',description:'Implemented a CRM, automated KPI reporting and financial modelling. Over six months, the team’s process improvements accompanied a doubling of project revenue and profitability.'},
   {period:'JUL 2013 — MAY 2015',company:'Broker Finance',title:'Client Services → ELMA Implementation',description:'Progressed from client services and financing support to leading an ELMA implementation. Mapped and automated processes, defined development requirements and established KPI reporting.'}
  ]
 },
 ru: {
  name:'Ленар Сабиров',role:'Product Manager',tagline:'Платёжные продукты. ИИ-инструменты.\nПолезная автоматизация.',
  intro:'Я Ленар, продакт-менеджер с опытом в платёжных сервисах, ИИ-инструментах и автоматизации. Превращаю сложные процессы в понятные, полезные продукты — от изучения задачи до создания работающего решения.',
  nav:{about:'Обо мне',experience:'Опыт',projects:'Проекты'},projects:'Избранные проекты',experience:'Опыт работы',earlier:'Ранний опыт',education:'Образование',degree:'Бакалавр · Бухгалтерский учёт, анализ и аудит',university:'Казанский инновационный университет · 2017',skip:'Перейти к содержимому',close:'Закрыть проект',details:'Подробнее о проекте',illustration:'Иллюстрация концепции',problem:'Идея',solution:'Как это работает',stack:'Технологии',back:'К проектам',visit:'Открыть сайт',top:'Наверх',contact:'Связаться',footer:'Ленар Сабиров · Product Manager',
  projectsList:[
   {id:'ludobot',name:'Ludobot',summary:'Автономная торговля на Hyperliquid с решениями ИИ и контролем риска.',tags:['ИИ','Трейдинг'],idea:'Объединить анализ рынка, торговые решения и исполнение в автономный процесс, сохранив прозрачность работы системы.',solution:'Стратегии собирают рыночные данные и состояние счёта, получают решение ИИ-модели, применяют программные ограничения риска и исполняют ордера на Hyperliquid. Веб-панель показывает стратегии, позиции, результаты и журнал каждого цикла.',stack:['Go','Hyperliquid API','OpenRouter','JavaScript']},
   {id:'health-tracker',name:'Health Tracker',url:'https://health.asg.travel/',summary:'Расширенная MCP-интеграция для работы ИИ-ассистентов с Google Health.',tags:['ИИ','Здоровье'],idea:'Сделать данные о здоровье доступными в разговоре с ИИ и дополнить их инструментами повседневного мониторинга.',solution:'Расширение существующего открытого MCP-сервера Google Health: добавлены запись питания и серверное подключение дополнительных пользователей. Проект соединяет готовый источник данных с ИИ-ассистентом и дополняет его практическими инструментами.',stack:['MCP','Google Health','OAuth','Node.js']},
   {id:'context-study',name:'Context Study',summary:'Общая история обучения для ИИ-преподавателей — между сессиями и моделями.',tags:['ИИ','Обучение'],idea:'Продолжать обучение с достигнутого уровня, даже когда заканчивается разговор или меняется ИИ-преподаватель.',solution:'MCP-сервер сохраняет занятия, письменные работы и повторяющиеся ошибки в общем журнале. Каждый преподаватель читает одну историю, но ведёт собственные оценки и план. Следующее занятие опирается на уже пройденное.',stack:['Python','MCP','JSON-RPC','Локальное хранение']},
   {id:'defi-assist',name:'DeFi Assist',url:'https://defiassist.github.io/add-on',summary:'Отслеживание криптокошельков и DeFi-портфеля прямо в Google Sheets.',tags:['Крипто','Автоматизация'],idea:'Собрать разрозненный криптопортфель в привычном и гибком инструменте — электронной таблице.',solution:'Дополнение Google Sheets загружает балансы, транзакции и DeFi-позиции через DeBank API. Обновления по расписанию поддерживают актуальность таблиц, а сводный дашборд объединяет несколько кошельков для анализа портфеля.',stack:['Google Apps Script','JavaScript','Google Sheets','DeBank API']}
  ],
  roles:[
   {period:'2022 — СЕЙЧАС',company:'Независимые проекты',title:'Самостоятельная работа над продуктами',description:'После завершения работы в МТС Банке развиваю собственные проекты. Текущий фокус — автономная торговля, ИИ-интеграции с данными о здоровье, непрерывное изучение английского и учёт криптоактивов.',tags:['Продуктовые исследования','ИИ','Автоматизация']},
   {period:'ИЮЛЬ 2020 — МАЙ 2022',company:'МТС Банк',title:'Руководитель развития сервисов СБП в эквайринге',description:'Участвовал в запуске СБП C2B и B2C. Прорабатывал пользовательские сценарии, бизнес-требования и API для мобильного банка, мерчантов, POS-терминалов и e-commerce. Управлял бэклогом и согласовывал решения с аналитиками, архитекторами и командами разработки.',result:'Курировал от банка внедрение C2B в розничной сети МТС. На четвёртый месяц сервис достиг 10% совокупных продаж сети.',tags:['Платежи','API-интеграции','Запуск продуктов','BPMN']},
   {period:'МАЙ 2019 — ИЮЛЬ 2020',company:'Ак Барс Банк',title:'Менеджер направления эквайринга',description:'Работал над запуском СБП C2B: собирал требования, описывал бизнес-процессы, готовил финансовую модель и координировал приёмку функционала. Сопровождал подключение крупных партнёров и согласование регламентных вопросов.',result:'СБП C2B вышел в промышленную эксплуатацию; сверка реестров эквайринговых операций была автоматизирована.',tags:['Эквайринг','Финансовое моделирование','Автоматизация']},
   {period:'ДЕК 2017 — МАРТ 2019',company:'МЛК «Гермес»',title:'Маркетолог · внутренние инструменты и автоматизация',description:'Помимо цифрового маркетинга, разрабатывал сервисы для логистов, менеджеров и финансовой команды: подбор перевозчиков на обратный рейс, уведомления о загрузках и конструктор предложений. Создавал дашборды эффективности и инструмент планирования платежей перевозчикам.',tags:['Внутренние инструменты','Логистика','Дашборды']},
   {period:'ИЮНЬ 2016 — АВГ 2017',company:'«Эффективные Решения»',title:'Проектный менеджер',description:'Переводил задачи заказчиков в прототипы, пользовательские сценарии и требования к API для веб-сервисов и мобильных приложений. Прорабатывал логику распределения заказов и расчёта стоимости поездок, координировал разработку и тестирование.',tags:['Прототипирование','Требования к API','Разработка','Axure']}
  ],
  earlyRoles:[
   {period:'АВГ — ДЕК 2017',company:'Фриланс',title:'Руководитель проекта',description:'Определял объём MVP, собирал команды и координировал разработку веб-сервисов, требования клиентов, бэклог и рекламные кампании.'},
   {period:'МАРТ — АВГ 2016',company:'САП Инвест',title:'Маркетолог-аналитик · частичная занятость',description:'Анализировал рекламные кампании, вёл финансовую модель и внедрял CRM с расчётами на PHP и SQL.'},
   {period:'МАЙ 2015 — АПР 2016',company:'Артус',title:'Проектный менеджер',description:'Внедрял CRM, автоматизированные KPI и финансовое моделирование. За шесть месяцев командная работа над процессами сопровождалась удвоением выручки и рентабельности проекта.'},
   {period:'ИЮЛЬ 2013 — МАЙ 2015',company:'Брокер Финанс',title:'Работа с клиентами → внедрение ELMA',description:'Прошёл путь от работы с клиентами и сопровождения финансирования до руководства внедрением ELMA. Описывал и автоматизировал процессы, формировал требования к разработке и систему KPI.'}
  ]
 }
};
